// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file yolov2.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name

using System;
using System.Threading.Tasks;
using Windows.AI.MachineLearning;
using Windows.Storage;
using Pabi.Models;

namespace Pabi.OnnxModel
{
    public sealed class LearningModelYolo
    {
        public LearningModel Model;
        public LearningModelSession Session;
        public LearningModelBinding Binding;

        public static async Task<LearningModelYolo> CreateFromStreamAsync()
        {
            var modelFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///OnnxModel/yolov2.onnx"));

            var learningModel = new LearningModelYolo
            {
                Model = await LearningModel.LoadFromStorageFileAsync(modelFile)
            };

            learningModel.Session = new LearningModelSession(learningModel.Model);
            learningModel.Binding = new LearningModelBinding(learningModel.Session);
            return learningModel;
        }
        public async Task<Yolov2Output> EvaluateAsync(Yolov2Input input)
        {
            Binding.Bind("image", input.image);
            var result = await Session.EvaluateAsync(Binding, "0");
            var output = new Yolov2Output
            {
                grid = result.Outputs["grid"] as TensorFloat
            };
            return output;
        }
    }
}

